### ISSUE TITLE
Only one ID is returned

### ISSUE THREAD

**Issue by hrmoller** [a-r-d/youtube-link-to-id#1]
In strings containing more than one youtube link only the last ID is returned.

In the example linked below it is expected that an array containing two IDs (`["D9TpswDIBS8", "9bZkp7q19f0"]`) would be returned but only the last ID in the string appears in the array.

Exmple at tonicdev: [https://tonicdev.com/56f00e169342211400978639/56f272fa9230381100563edb](https://tonicdev.com/56f00e169342211400978639/56f272fa9230381100563edb)

**Comment by hrmoller** [comment]
Created a PR on this issue: #2

**Comment by a-r-d** [comment]
Merged bugfix and published new version to NPM (v1.0.2)

https://www.npmjs.com/package/youtube-link-to-id
